[workspace]
members = ["notizia", "notizia_gen"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Louis Meyer (H1ghBre4k3r) <h1ghbe4k3r@dev.bre4k3r.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/H1ghBre4k3r/notizia"
