[package]
name = "notizia"
version.workspace = true
edition = "2024"
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
notizia_gen = { path = "../notizia_gen/" }
tokio = { version = "1.49.0", features = ["full"] }
